### ISSUE TITLE
use toml as configuration section?

### ISSUE THREAD

**Issue by GopherJ** [kkiyama117/coc-toml#10]
Hi, I'm wondering if you mind using `toml` as configuration section like many other coc extensions:

- coc-prettier => use `prettier`
- coc-explorer => use `explorer`
- coc-rust-analyzer => use `rust-analyzer`
- coc-git => use `git`
- coc-clangd => use `clangd`
- coc-go => use `go`
..

etc

I think it can be a good practice, so that other developers can also use `coc-toml` as a default and contribute to it

if you don't mind I can make a PR for this change

**Comment by kkiyama117** [comment]
That's sounds good! Any contribution is always welcome, I don't mind contribution of any other people. So please make a PR if your work has already done.
