### ISSUE TITLE
Update dependency name

### ISSUE THREAD

**Issue by duongdominhchau** [kkiyama117/coc-toml#13]
At this time building the package we will see this warning
```
warning rollup-plugin-wasm@3.0.0: This module has moved and is now available at @rollup/plugin-wasm. Please update your dependencies. This version is no longer maintained
```

**Comment by kkiyama117** [comment]
Thanks!
I'm updating dependencies now and please wait a little.

**Comment by kkiyama117** [comment]
@duongdominhchau Now this warning doesn't appear with the update of dependencies. Please try it and give me mention if something wrong exists.
