### ISSUE TITLE
What Command Should Be Used for Formatting?

### ISSUE THREAD

**Issue by theSdev** [kkiyama117/coc-toml#14]
I installed this extension to format `toml` files, but I don't know which command I should use. For example, coc-prettier exposes `:Prettier` command. What's the equivalent for this extension?

**Comment by kkiyama117** [comment]
I'm sorry it took me so long to get back to you. This plugin uses the [format of coc.nvim itself](https://github.com/neoclide/coc.nvim/blob/a1688fc34143b1b7a25ab8c98438088199863e35/doc/coc.txt#L1291). If you want to use it as a command, you can set it up as [described in the doc of coc](
https://github.com/neoclide/coc.nvim/blob/master/README.md?plain=1#L220),or you can enable it for each FileType as a feature of vim.
