### ISSUE TITLE
`duplicated key` error when defining a super-table afterward

### ISSUE THREAD

**Issue by blurgyy** [kkiyama117/coc-toml#15]
Hi, thank you for this wonderful tool!

I was recently playing with some TOML configuration files, and I have found that `coc-toml` throws `duplicated key "gui"` error with the following TOML content:

```toml
[gui.gtk]
# ...
[gui.qt]  # Error: duplicated key "gui"
# ...
[gui]  # Error: duplicated key "gui"
# ...
```

Yet, if I move the last `[gui]` section above the other two sections, the error is gone:

```toml
# No error
[gui]
# ...
[gui.gtk]
# ...
[gui.qt]
# ...
```

While the above two TOML contents can both be properly deserialized with the [toml Rust crate].  I have skimmed through the [TOML spec] and found that it has an example saying defining super-tables afterwards is OK:

```toml
# (Copied from https://toml.io/en/v1.0.0#table):
# [x] you
# [x.y] don't
# [x.y.z] need these
[x.y.z.w] # for this to work

[x] # defining a super-table afterward is ok
```

So I think there might be a bug in coc-toml, it would be great if this can be resolved, thank you!

[toml Rust crate]: https://github.com/alexcrichton/toml-rs
[TOML spec]: https://toml.io/en/v1.0.0#table

**Comment by kkiyama117** [comment]
Sorry for the late reply. A library could cause this problem that it relies on, so updating it might fix the problem, but I'm overwhelmed with university exams right now, so please give me some time to work on it. 
I think all I have to do is update the dependencies, and if you would like to contribute, I would be happy to do so.

**Comment by kkiyama117** [comment]
@blurgyy This issue has been resolved in the latest one. Please update to the new one.
