### ISSUE TITLE
formatter is broken after v1.1.0

### ISSUE THREAD

**Issue by GopherJ** [kkiyama117/coc-toml#21]
hi @kkiyama117 the formatter is broken after latest changes

**Comment by kkiyama117** [comment]
@GopherJ  Sorry. It works in my env but revert npm's one until I check what's happening.

**Comment by kkiyama117** [comment]
@GopherJ Now I've deleted 1.2.x from `npmjs`. But one that uses same versions of each dependencies causes `formatter not found` error in my new test environment, so I need to rewrite almost all of this plugin to resolve this issue and update dependencies.

**Comment by kkiyama117** [comment]
@GopherJ
Thanks to you, I managed to update to the new one. Now that the latest one can format files without throwing errors, please update to the new one.
This problem is caused by `node-fetch`, but I can't find what was dropping the process when using v3 of `node-fetch`.
